// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealStateDotNet.Data;

#nullable disable

namespace RealStateDotNet.Migrations
{
    [DbContext(typeof(RealStateDotNetContext))]
    [Migration("20240322235737_type")]
    partial class type
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealStateDotNet.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateAcronym")
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("StateAcronym");

                    b.ToTable("City");
                });

            modelBuilder.Entity("RealStateDotNet.Models.State", b =>
                {
                    b.Property<string>("Acronym")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Acronym");

                    b.ToTable("State");
                });

            modelBuilder.Entity("RealStateDotNet.Models.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("RealStateDotNet.Models.City", b =>
                {
                    b.HasOne("RealStateDotNet.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateAcronym");

                    b.Navigation("State");
                });
#pragma warning restore 612, 618
        }
    }
}
